#!/bin/bash

name=$1
author=$2
libraries=${@:3}

mkdir -p {dist,src/{core,components/App}}
touch package.json src/{index.js,index.styl,core/{base.styl,helpers.styl,helpers.js},components/App/{App.js,App.styl,package.json}}

# Package
# -----------------------------------------------#

header="/*!
 * $name
 * @author $author
 */"

package="{
  \"name\": \"$name\",
  \"author\": \"$author\",
  \"version\": \"0.0.0\",
  \"scripts\": {
    \"js:watch\": \"watchify -v -d -t babelify -t partialify src/index.js -o dist/index.js\",
    \"js:compile\": \"browserify -t babelify -t partialify -p [minifyify --no-map] src/index.js -o dist/index.min.js\",
    \"css:watch\": \"stylus -w -m --sourcemap-inline -u nib -u jeet -u rupture src/index.styl -o dist/index.css\",
    \"css:compile\": \"stylus -c -u nib -u jeet -u rupture src/index.styl -o dist/index.min.css\",
    \"sync\": \"browser-sync start --no-open --no-notify --no-ghost-mode --no-online --no-ui --port 3001 --proxy localhost:3000 --files './dist/*.js, ./dist/*.css'\",
    \"start\": \"npm run js:watch & npm run css:watch & npm run sync\",
    \"dist\": \"npm run js:compile && npm run css:compile\"
  }
}"

html="<!DOCTYPE html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<title>$name</title>
<link rel=\"stylesheet\" href=\"dist/index.css\">
</head>
<body>
<script src=\"dist/index.js\"></script>
</body>
</html>"

css_index="$header
@import \"nib\"
@import \"jeet\"
@import \"core/helpers\"
@import \"core/base\"
@import \"components/*\""

css_base="rupture.use-device-width = true
jeet.max-width = 1080px

:focus
  outline: none

*
  box-sizing: border-box

body
  reset-box-model()
  font-family: Arial, Helvetica, sans-serif line-height 1.5
  color: #333

input, select, textarea
  padding: .55em
  font-size: inherit

input
  background: white
  border: 1px solid gray

a:link, a:visited
  color: blue
  text-decoration: none

.container
  position: relative
  width: 100%
  center()"

css_helpers="ir()
  text-indent: -9999px

va()
  position: relative
  top: 50%
  transform: translateY(-50%)

responsive()
  display: block
  width: 100%
  height: auto

caps()
  text-transform uppercase
  letter-spacing 1px
  font-weight bold

arrow(color=inherit, pos=top, size=8px)
  absolute: pos
  margin-{pos}: -(size*2)
  border: size solid transparent
  border-{opposite-position(pos)}-color: color
  if pos is top or pos is bottom
    left: 50%
    margin-left: -(size)
  else
    top: 50%
    margin-top: -(size)"

js_index="$header
require('babel/polyfill')

var App = require('./components/App')"

js_app="function App() {
}

module.exports = App"

js_app_package="{
  \"name\": \"App\",
  \"author\": \"$author\",
  \"main\": \"./App.js\"
}"

echo "$package" > package.json
echo "$html" > index.html
echo "$css_index" > src/index.styl
echo "$css_base" > src/core/base.styl
echo "$css_helpers" > src/core/helpers.styl
echo "$js_index" > src/index.js
echo "$js_app" > src/components/App/App.js
echo "$js_app_package" > src/components/App/package.json

npm install --save-dev browserify watchify@2.6.2 babelify partialify minifyify browser-sync stylus jeet nib rupture
npm install --save $libraries
